---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: radarr
      version: 23.28.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      stopAll: false
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio-restore
            dest:
              enabled: true
            src:
              enabled: false
      media:
        enabled: true
        existingClaim: media-nfs-pvc
        mountPath: /mnt/media
    ingress:
      main:
        enabled: true
        hosts:
          - host: radarr.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: false
          nginx:
            enabled: true
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    credentials:
      minio:
        type: s3
        url: ${MINIO_S3_URL}
        bucket: ${MINIO_S3_BUCKET}-radarr
        accessKey: ${MINIO_S3_ACCESSKEY}
        secretKey: ${MINIO_S3_SECRETKEY}
        encrKey: ${MINIO_S3_ENCRKEY}
      minio-restore:
        type: s3
        url: ${MINIORESTORE_S3_URL}
        bucket: ${MINIORESTORE_S3_BUCKET}-radarr
        accessKey: ${MINIORESTORE_S3_ACCESSKEY}
        secretKey: ${MINIORESTORE_S3_SECRETKEY}
        encrKey: ${MINIORESTORE_S3_ENCRKEY}
