apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:y9r6t5wYkg3BQqwtixwlFpWbK7sot5sYT/kgONBU4pEoohlkqOb93f+KJrphfi0G0q8eN/TRCJt9ObsRh+EBEcZQppSlI3byFVOqlE4zYeC2spXR19ktMjo6K2kx+Bc38vmtV0E1+VeHigEvgRWEq9IysoJN/iEocQHY+cVIpaqvlGSbC2D/aDdNF09M/wMCK4oL/o38gm9kDsBhyFnRuv5hqNfQ0x2cKVPz9NLE/t0aOMNqDjTRFHvD/Om8GLLUsW23LdeujSXawpEBWUtFEeZ0SZhgQKM4ivg1gI3zWXR7bQFJiqldkbKBLJxhYB3yIOxiKVlbZ0VEuhRWijtqU2a1frqto0sN4PsV8/HYRn2BDeCM5bebeTGYJUm9oLCC,iv:4DSLXF3z6dWk+vf1jS3oLYYNoIKNTHsOvAsW3a/4wTA=,tag:n9lxHq1mE7K7lSqxRAzAzw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Pc/H/X79xzikN/V2uU2U1LGWr40DTVYcPaDfhLvNPG7eaMP0ptJKhQFMUYmoHw5fo3I8ShEdvG32196HLBRk51ewBsuLYewGoypdksCb/NlDn9WrfFf3E73KIxzY8KlrVl5WmwSKDNrdr8wP9MxUOedfoablY7b9rYtsgnPR8OFXFv1EZp9z+dyqHEGY+MkrML3Dg52NqvZlydduOUFjWcBS8emukq8JY/KK2PjyYWIyGsFj3FQTGiN7yfPvi5Ypgmwd4Wqn/irQzOCivw==,iv:/4MgYEMaTbtNQkhVh+nLEC48uUmURyo5iS5rV7r7vHA=,tag:k+qxjfGgudcb+38bE7DXrQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:v777Xu2ybAd/ZLH5gq0f0J/Iyhy1nKG21Kq00MSWDZb6Z2pHVhULqgW9URcoNrGbHBErI+FDIR/Em0v8a7SDcXkoWQH/994yM4IHh5s4v0s/f5hGx7GeWsqXymXgA2d4xGsFnlPI4RFP28pot8Atc93N2RcX7nP5FcNuEHhTIPRLzrESAn1VRDc2Fx6IxMQ2vqK6Xhbilm2fDprD//2BMj7vknnVmqokROHs,iv:sMYiPZkGIvZRlfwzbiMSRI8PuWJo2Gv3lyDv1sZmXwI=,tag:idUDFfr3fBRGUZCL6LxUhg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVG0zZXZXZzVYaVZzeHdE
            bklhQkxKR0hkakthTEdMaEpab2U3SUdRY2x3Ck84NFdTNERlUkpPKzZSUEVLQ3FK
            bWoyNVpaaGtGVXdHb0dmcWswN3dPRHcKLS0tIHpIS3lIam01OHhQTEtxTWlUQWVC
            LzVrTVpCeVB5VEpBRWpLSEpMYy9DNlEK3sc0rKFY/NHGU/Fz6xOKY/is+fdZnCXD
            rXXwyjSqya3/P3BFSb3E3dn9WHrZT4cX2lUUdaHtv4Knu9u+LJSaqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-14T12:11:44Z"
    mac: ENC[AES256_GCM,data:1Og/T4TEofAYC+urUVjLn/bPevbdSHTOawVGcZmHuR9CqZ4vd0uPU2n1IQK8CNMhtcKGNtPDWcHvXEwqvH102umIETYFxs+jsSSuTmVuHhG1aeL54+EHae93zzC4R6WE/jioS//Uqh5doOpcUJE8j9qSibpRAjm/JLwig1x7YIw=,iv:4V6DCNcjbMwC1VxDMBimzqu2KXl9NMyCHlSjP14D1wg=,tag:B580Z9j0TiAscl3vujkhOw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
