apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MUfQnNq//KH6pSe3+nL0kL8Cbk5q4Phg9gJPjsvfVGyKCGbsI7T3O1g8GHGZQrU46Z4syjCSTi2M/VgYa9iZx4nAyY5/J5OH7WPx7i6Xu460DV4G5MseOY15t6anfRVOv13q9c1fJWj+vI/fTEhClYk/BxiphGS9Hpj3deniy43OikgYhyqg6ia5KPPQFbYq8EfnUSuW0PGFs3Kfsjuyh7xfhaMmh8xbIjIx+7HWPY2UQ3rH387BkFkZ05pKHkvlYKNpxKs5LgVFy/XW6Pt1Ha7u5211Tc1qdPKHAq+MfM3AWhFvy/3umldeLkLQEbcWwnEQYLN+pNEUPS4TapsOL0ZjIb1oi+b8cO2irLUX25bhpKeBCapCYML/T8JRQsoR,iv:wVpk60VTu6ZqWbS/64HW9TUHQCEfo/R8iI0oYK6XUEA=,tag:G6hgipvwzkMyrdICRIX6mA==,type:str]
    identity.pub: ENC[AES256_GCM,data:1SMdLfqk8WOVDnL7MB9SSVFzKe+hnTAPgSmlICF97XJxx+CEDf5g4ZgJ6roFBzlVOiOGZxONSxUD7eiLcI8K7sRa2LJq/S29kzpit3rczdXXhg0gHDIC4Q0TvFoLl/v4iUvZBfYmbTQ9rpADnlF20U13wGYJ+uL+JXyEjPoQB4jSt/TEEDeEsyqljS7WcI0ajte2F9WBFp9ZatkRtgFnWf3ikyhX9HRi+zqeRzajQ+ygVui2+b+ExbhxDGu6mVFi8S7vYOSh3TNE+E3i1w==,iv:Qa/J8/yrOVBgiMMJaU/WKbBKouo0gVHQR1uS8mir3JU=,tag:ZuoF5vcGh+AA9/BDwrIE5Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:uL7MM1nUge+lYOpsg7mmyAb8HtKSw82e6U6OTK0SWlFB5VdM+5uvPbQkt+YeILvb/D2/EPx5ns4cw77K0o3tAKr3mGs7sNG2XjAOB8TDmP3pDI1uPhWHIBQg/BUcXCihTjYP774ULP6m6mC1h9dEm1hldgnqGyBkggguz3MkB9e8GgiLrUqS2zt/ocBsB/ozj8XW2e7gXd6rhPh2I4RgXTrSASC6h5NIE0zT,iv:/EUrs0ui2wx9TV8apyqe+qW9V+TbZoyHZsRtabRq1J8=,tag:/+RyVLj0uIg/3WLKVcF2Dw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUVZ6bi9wb2NXcmJROVhJ
            UUVDYlA4bHh2eFFHQUVMdDV2TFc2WC83YkVVCmtUYjVveTBMSjNGWHpZUWlSK0pE
            dGR5Z3NjSDI0NjE0U3BGRWVHWmx0SVUKLS0tIHVjMTVjRCtENWVJVW1tN1BteHVT
            aGUyZW5DckE3eHk4OU9mdVB5NldOZzQKSDCu8Zv2vNdTiA7i/HW7q6Lwl+ZUCQKv
            9atKAc4oRddZ9DQuKTGvLkooM1BjJtpW5JKSMsIvOnA/UpfIuQ8Lqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T16:38:49Z"
    mac: ENC[AES256_GCM,data:Y1gRCaOUGbTj249TIaZQ6Gk0dXU4evwdJ8I2rARgt7dyTWYXZyfsJuqhV1cbQAVpHCkWHCr3R87rf8qhZCV6s9CV7juCoNkyfDF6zgZKDXiZ8Ys0yqOzPj3oQgXDjLA1bqc5wr5u2nPGjdWz+J1frsCp6VD+vdorV/8O7eJc7QE=,iv:LiN6kAPaLD/b0yEcRMRQMdHuy4BUlxWZB8WHpIS0YH4=,tag:LqFl9ARD2lV7PFG0QmDy7A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
