apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:il2mTrL6jhkm+Tiar84iGoYaGFFHlPEjClcGuH4gsVvdzRVTWUBjaUPThg+kz6IVPXVAczsL7C4SBlz2XKmGnlPF4GYuO+4mwVlYNrNou1r1enOiW/zyiY6lse2U5VIJeHbsnXXBRF4xE6bc8mJqis79GJgXTnwcYz9W0DSbzDAxdpz4FqYHOHTunBMJ4EhQYXHAN9PAgmhN3l1s0ZsyPyBOUPWYiMSxa+ld5y9TpF5TkyhhbYRK7JOXrzNkeVL14ZNnV21KE7wPh4ZI5bAkfva1z2O2vmonJgcz22J5NYDwwFb9KCHbcBgu2u2IodppB9vGjjLgaTKLZRuvj/uIG/vx8ijroeIyCPUrupFns2waf7TmKTa7fyyf9FsP2Rfb,iv:3J6gNZhIApyDPkDJRV6mvmOPmBaorFtLNKzhI68gSCU=,tag:aySGHf6XzCNLddDiHUvvOA==,type:str]
    identity.pub: ENC[AES256_GCM,data:5T3nar+IJRgxADRGLzsmHuxqya8+M9/MMnp4lVS79gWOR/CfTn2s+VMVesa64EDqcq3C2T/V+kdlsuhrw3NCw1pzkHQ9Tz49xJnwa9zWGjqJkWw8LgHO6tknr2MPt1b+tYp5RVIcdcY+xGsriKGIiimXRIuKo4m37Y1o8IyzZxb2ZSExZOfW80C1FlXexuCebZyTLSyZzLR3LBqZmQxXFITFp8CNbM2J7NR28HppSPH7VH9SJYsxGBx0L6tFW6oLkkWXQPWqDG54gPJPQQ==,iv:Ri9h48vhPv6gc0CkpUjoKK+Ks30t3yUn0TbwfufDOHE=,tag:mgxrb8tLfBA0z1xqq2yz+g==,type:str]
    known_hosts: ENC[AES256_GCM,data:BTqC17hfjqW9UYfupnbfDvpraVhSVG2yRmQrV8BbeitQwSEuKxsYKKXtKc/lA1UgHqh5+aGiYL06LDQI+FC0NObt3726hQ4c+9PGkcDmdVyL2xD6MPgeP2vFRtPI/tYUMy2RoSzT/HlE9jP/cbS84cA3FVgeLUuylfm9GK+GnwN6977yzeiE/cV56kou596M2FvlZBP7vD1FvB29W3iVJlXBCgUB0bcT0NrG,iv:pM34loF4VYscoS0WAdkFNZjxOYYJQJe7cSA5F4c/boQ=,tag:17KbZHGrsUKUj6tOgS/JrQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd2VUZDhac3A3YXVqK0pv
            TnZNSkN6RGFPdUdUQXRPbXZ5d0l3UDBIK2dVClRWblU0L05IM0xjL2JDM1UyRjhS
            Y3prS0hrQW9EUkkzVzJLc3hNR2pBa00KLS0tIFFaMExTR2ZiMStiOC9RckZzNi9J
            VTFIVHR5aWtqYUpXV0V0TDZJRjVWMDgKpGNa4tNnSVbPEnnWFCyj87hiu9V9CzgU
            JRGoviWuF8sAU6M6wCMrGnHODNyQvAOdBTHJ1hCM4z8UXKg6FtRdTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-03T21:36:14Z"
    mac: ENC[AES256_GCM,data:bJUXlmD0E8t3JRE8/yrfwfb0v0noNQk1jxfBucLr13Yvx2YwKDfkAiLWwyNBlpHc7mum3cCw5P+vQ5JwdV+sUG3LSubIQ3BVZAWeQeDbQsNnYfV2qp440lD7Eo5+5H+ztJhiyFn9iowymnkZRdeSEXe8jICBu6b5bpX9L92Oweg=,iv:Z7KgWEeby5QGCDvfP2P05p2f9J6G1K4pNxTHRUmMmyU=,tag:hk7/RrX90aJ+dH2tReg+KA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
