apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:c2pXfA0l26W4k73vXwzA1oG5NYbi4TEc2vnXH6eKjGFd66Vea0Y9ozkhCBksNB9UWATq29fsuw1PmG95oXchhJsJTg7JVrr/YLXO31nfc88+0o7v7uxuz6Iam0lAAt6Y099/HTUOLe3OAtPXZ1V8EhcQC+tAsT0bXLx8qgEmVAx0eWuZcnH2Gcaqet4a+VkGLeLVLtAmXYOj275BEn9GUfEWVXANLAq3+Nc++GThoFXNs9r+fUghPzQjV7pQJphtkRi6pxtBiSL/tZOQsbvnmKtIClmeGwcUlgVzCepuueKxnzBSKuW6vNg5Rkdm/naYjEz5XJjPjIlDTYUqcgeK2jeiFT44Zv57cWe5MdbDZJ4+enktODQz1DApV8qLaEk8,iv:vJF7QuJprUhre3Tu5LxpmPscGnK1H4MkRIm02PRDXJY=,tag:7v4RDbTUMJmBW9IGczEoNA==,type:str]
    identity.pub: ENC[AES256_GCM,data:2eLC1YxmilMrlOM1oVyXilCVx2VS9Sp5kLA5BI9gxbKRT+nSo8ftyxDx/cvYedbewpUSUOslnQGT2+5qNZ3InF8witFTcMls6WVhc7Q54Xnn5RC/MbzbHXxqiYnVPY6kZNCcMaYUWMw1lVNCR6MmwpgAOA2BT8cOaexLF344RoZ+FZy1I1XOIzdzPlQ0vnZm4nRpdBKy8rHT5Z5tHEBgjHgfiuWFuK059nwgB8yjcNmys21LCMfpoF9mN1QaIWsqfRKYmBCn0sdb5DJWkA==,iv:Qq66AzcuXukTivF/jSyjwyuFSHQ8bmgsPlhV/yAKcXs=,tag:m3WOKZ42V1ZlDbAZ0D5AQw==,type:str]
    known_hosts: ENC[AES256_GCM,data:wl5HPpRd1eBWzjU2YPMRv2r3sbPr1cNzDdsyQvrI4P97uIEF22gybjWu43czIVJbxNvsr++MsVq/WIrDOsF/n3wpbmxVLW/pL7EnieFQeHtfcdfR+EFWAxJgmXOIuOBtLiU1ZsEYXYjw+5CUZ7cKINdG6nQY20vXr4oZUf9gRMRmP/zOSeqxNNUvDNULmsWbSHWeZjqcOEcLGPk7S3OWKtzH2Mr5GBjveAYQ,iv:M+25ct2+6Gc5LU+eKtcJxznx5bDpSq1YmJrgBJNROyg=,tag:EnR9WlT/kGDANZZ60bjJug==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ3JKOUd4WlNaT0hGQUYr
            N29MM3VCcUJOMFM2b29BV0RtZVFqdW5BaVhjCjRuVk43UUs0bzd0ZzBMdVUxNG93
            RDZjQVNOK2hzVjJ5Mlo1VDluajRUMkUKLS0tIDhhYkJOY1daTndBbUtsekE5TitM
            T3JnVWprRjhVVmNUOUd6ZGtibktWRlkKyP3vngW/TnYwP2ZguOKyeokl7L+Pv7vs
            xIqi3poIhLEp9uAD5ulUa+jIZcPefoD0e+oF+2eKdSQVDcxq9i55mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-10T21:36:35Z"
    mac: ENC[AES256_GCM,data:PBxYqSAl8dmb56m82/jFJ2CDCP4tbPU8lg9o+7+W1Ow9wCPx/jm15kunDD54BpjXidrleiGVKb6sFl5+357dXatc/rvMachpvZ0+MUXwuKi2lCaaa5F5CVAwPAcV91MfxKxvkUA73sqAiFjrUdIRbONHM5BMBZ3yId1lSMcMGXQ=,iv:0bdaT27WFJhZ3hyiKVJwCScXgAwiFoNzzRZUurBWu7U=,tag:wLhJHd70okPvWECfNDIJTg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
