apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MCsM3ANfJiSJWMVS6rf1gorj61kIi/I//dY3ZeTNZxwH/S9hQY79eNBLVJFW8dr7RmgvPwnklRyO6O12vTKZbf20/VBx1M2xjM7Xe/5JUy7B0bZl+qc4Tiz1YXnMcDZJtqOgPZKu8bol+jLzHBb7CFEoDrNrEgHwTAOj5npU5UVYBT/kjNzwrVlup6PDYrlxmyBtW7DUGuk/Zlg0fZs9V+7xgCgqJDvWQ5rRiJcdNfJgzpVHMs4wOtHrix83Qc5eXz+DmSyw8GzfsYwPrOjMrNkghGFvkuHpy9aR2HTQ8XFPOKVyDVFzS77eMX0xQH3/6meBZHrSIGTNxVRugTtiYcq0qzxmAtXqta+WRfIy7Sp7s9j2qdUTRe7qd3AHRqOG,iv:yFT2NRmwfRkerOxzEB+wWZCU983MQRuMtDixTHR3Nhk=,tag:tOPRJTHH97vpO8smoFX+TA==,type:str]
    identity.pub: ENC[AES256_GCM,data:jxKSbGgQDAknNEKHVSV9YTKqT/HatouiGWKoCBhBNMnXiTsUKXkNKK8EwmzWskTNPN+uL8JRcLwymAF2Cpi1MTDNNTzamYKzPbc86HJbyDCEdb5v0IOylqw/bO+1T4ftWY0s0mv2mITSuAuNoFfN8nQGjDAa90b1ionlvnH8S1M6gjLis/Ukep0PJ1OpqMRBdE/Sowsy5L0U2tEbErZd5ti/YmA7eJAaetthr3KXtuvbBcfuYmgoQI/d6HBhnzOV5aPZerw/JXmKh2zMow==,iv:HIyBzGrrrZUXRnAoLFD92abaMdhAqb9SqXjULN6WqFo=,tag:HOBExtCE320lxn2ghjRJCw==,type:str]
    known_hosts: ENC[AES256_GCM,data:8c3psCoiwELAaga9z+LbOW4RwACrbDGiMHnMddwdpVoukGrf4/hv65VEgNB78rSvsVJtXYsxnQv/6A4Lg+efRAczZv2UEB5EmyioHuqOnraawVTAAuClf6HmwaLMAseSRUrCWfqlJGVqB0NtI/w16bbINozdEIOYsdQUCLqyAQqA/4LU60wNUYt7XouKD4hEhny1jxOs9UnFflHwhTdQ0Uqfqn//k0TPQ56t,iv:Yiu6RomD3tzBIbFBE5iGbykSA6bN5duXeiTkkOf3Rg8=,tag:rBP+Z7FrxSjsZBbkvMrG9A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5T1JSQ1UvZytQNFJWZWht
            OC95ZEVEQk9YWXQrUTdseWY2bHpkanRKT21FCi9lNHQ5QkFOVytyalFqT0l0bE1X
            ZzR0WlRjT0hOdENBOUlXM2FHZUtRYVEKLS0tIEloNnlXUUlyNGgvZ3NCTi95dGdo
            SEFwNEx4Vit3YVQ0QmtWV1lxOXNxdUUKdvOC/DFH6Z6v/Y9K4yGBgbQky/8qWKnX
            K6zpbAE6AdU//fwjL45PwYH1uB/WaMWGSpS2pc9VkYITtwfD/OdscQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T15:13:29Z"
    mac: ENC[AES256_GCM,data:mo3SwJ7kT3x6GDjvcl6QudGNk8fhIv5AYbK5380xVxMJUuvDDVMF+J0kZMgGIpDMsrznLNm+ajOWUpU2NJA/MGuWH/XdQ2qoOmwJbyPpZOL6anQxYsxlQmFzSQqSTPtRHs9/tfUCMOKjKy/3EFQ6jSNfOcLhIUw0A6UzJexMB/w=,iv:z5atK2NWNzeyU0PcTUa2hCBDgn5sMN+eOliSpz2PKOY=,tag:JgofSuj9ku1rJvtE6WUwVQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
