apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aCKqZbvRrTpJph1l/SdG+0mI2zvFeTz8iGflK7Hl5Q6wxyQ3QRiy41o0j9sn4frCWdOJ1uRHS5QtcS4ONFBaheKeY+VJptfQs/Edf7SvMnTLK4as7sec3tQmTHJN9YbURV+onHC1WXgRhDcDZfnwnkkwwZitcdI+XKvU38UaPgUulHd3TaGXjRMNOh4jjOcer214B6irA24yE8DMIK91dxKd6gfjcNz4zHNQ6nbUTioHclWrnZN9WSmmFZLEMEDfDK4mVcUDeFg/88Mimzp0ZKD5IUoVaUOjcBOgPIDNQQ3t/nxENyoedjm9LsXo/A13lOHpqGIt5baz3erIbLREcYy9MT71vPGibjh4IF0Jbt9yGDDtx9zGJbxGSt/xOY9w,iv:9zQxO6xjvePQ/9Obnn6zmnZXyq8P3krA/Y8+Nn2FldY=,tag:NUGuAhsyalMb4U8d7nFnOg==,type:str]
    identity.pub: ENC[AES256_GCM,data:rUSQE5P6qZPnho4UnSeKnFnNKats6LJb0QAAvVsSCt913VQeIBT/F0KiKhP+AFvHlpAFiJ2joTI7JGPTtWp2UZN6L1zJIX46XODaEGg+rzVdh6Ah9bBQRP+j9yZJoHnAcIFIj3fl1OlJpcwv6QGNKydqZkwqbbT53+3GhUensIe7hQ/RMViNVL4P1OnrylEZdG5IyY0sZhowbqIXjhw14LxIiFFhqtIZEySl4y344rv7/zBawino1XJqQlXsEkZcFMS1QawwiIGDvg3+zw==,iv:XQwAlX5AJJtWxAmNPZ3pFDAUu0S7HdgyLDO5DTMCXwA=,tag:SI1a4v+/j3u5U2QHbaqxnA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ET2v+Xm9UbC2oricpHfiKfBt/Y4tV9R2xWpgDGeYO7j41OJL/SGnTOs9EIgFFtJEtqMh2eTpp7ijHPhkA1YikgWR/pRJpP7LJDwBSkRGPGL77OELW+06rKivog9nqRiMAbr3sRfXLm1BySVZvVU6ukUF/sCLhF4PjLU3z2BFlxWYceUtumpv5HHzp92Boin1KXJqhYdM1jQsuMMXdjtsyiEP79ILzysTV8wA,iv:k3qs7MWzRcCL+3e4zGXkBGrLzg2vK7S3pNhGLv1kNJo=,tag:ozBpPmQKETNfRINiu65n8g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbDhwZVUzNVFSTDBtNlM3
            SnAzRGtJRk02SG1lRWJkb1Vqc09wSXRsY1Q4CldyUVJXZmJRakxFbHRpTnBmdXdK
            QzMvWTJ3V2JTODdEQitRYmpIUzd1aE0KLS0tIHExdFpqU1dhZC9BTW02VWdkbmxh
            RjlJNzdXMUcyVDNSWEJpNnExcGxTUWcK7yLA4ZBKycarSHsdb9Z6IKVtXwIdiUAS
            SSn1+mxByzdmZtaRUm0V6MVxEes0+Fn+CDDiBgef5720WatOoJnJOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T18:46:56Z"
    mac: ENC[AES256_GCM,data:88ewcTKK/DVk7h6lXVp9/mbIds9LZJPahfPVhoKhjkO9qqLk237f1Q16uIiKJ89kTtgmeDeF2rZDC8V1+Vhn5AM3DLUN7YBNINEFQ8wVHvgweNnpGnMwlQ6J73Pd383MgPOLjthvbvzaIQl4j2dPshDf7ta7dCEtBCQLubpDAkQ=,iv:vuJI7ln18z7nTlZXz1kksYvTbgUqvZBcN5hVkP5VTfE=,tag:jDfag/FCcju2fWTJUhaDsA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
