apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TffaUMP5B8dhk6coQSPDwCmV79zm+O6IC8KaQETAU/c3Wvn+STwJk3RjLcF+CEh+MNF4X9cn0h9JdbRTy9IWTQP8kPiDbS4NkjQT6F0/kq49JpWlkVVmkqjeGyKeWUy7MGFaQ+f0JBZ+Zh5lEkGkM2HNilY9YLed8t8k7gl7EycKxyt5JYTzD+DatLOGk30pBlDUAKzhxxug5DDVr3O+DCLBJezJTTfUHgck5RVcqHfI7BnSe9oznGjYfKLQlpAwI1xaUqcrqKpzE/0oFC0Bnf7IifFIrrz3touiFVcnxquRTgnYEtJEvWxghHvmYlV0Zt23CunF/aoxjWVJ8DgXphtwb70CNUs4esb/tDMritz/CHTXWsi4puGQpe9UYXCc,iv:/iOJgL7p0Vdxmsv5cwo9W7YvNbuRxU/0FnGSaA8sXPQ=,tag:ljbPpQlnYTeNoU8LCyPd6A==,type:str]
    identity.pub: ENC[AES256_GCM,data:7KgSnaBUELyWKVw5wMq6Bh3/Bnq6Nt+Bhz0y36FzxFmxE44Qj9ZX2g0AsDXgA+0O88si5Y9kp3PhHZXeiD2cxeGG0jZjUBMAtMK2MdbczKEZh0J47q6v0I4MZ6jRgg12atX9vNdq1oBBChuzUzRfqgU257gvJPUxI8nHMHc5S8l7mEMhQ3/Eu2vT2qC212GAkwhq2IgPuaABF2SDn4DbIM/1r0pZK+fzhg3ooiG+tQqCUoSmOqCKPRcxMm5+As2NsX+sFnuPW7lKaHhbWw==,iv:UgZUgYGtbcNoFE9S0PEA3ybD9u5kTr+yDFBHaPgAdhY=,tag:xyzBBsNgdZ4FnhXF7p5r9A==,type:str]
    known_hosts: ENC[AES256_GCM,data:Gazdg/pR9X1UKTiWrPaN1q/Z3y4f1oMoS1lj2NVX6SXp3+y72gESPFk8v0W1HteYQonOvawwtoNx2pqpPUqJfcfEDqb1HxRYz2aF7qosPsEfd4BN7XMw9KbY+ZpesR6A1b16aENewwRj2aElfkA4GPq87iJV5QVUZm2qpiHQz9pmUISoeebOAsxcv0NFsFJMcrPM6Ryb6UGg2YnMMpYhoLaF2puztmsUuVvW,iv:1V5GOAA/IwRBAjonZkxMWaz5B8GFl34xcGMlhvwsA1s=,tag:nRMUTB2FX2AN0AB3z782Wg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRHcrTUxxcExheWVPL01n
            OVgzWUlZcC81SFZVaGhEQVFwV1FodDVaZ0FNCnBNTEVUenNvMTg1RCtKQW12aUJy
            WVhZSTJOaTB5Y3g4SS9qWkVHR0xSVTQKLS0tIGFGZk5QU3FZTHNnV3FvZXdPNG54
            UWZxQ1pQd0R5dnBaZXIzbXFMR3ZwaFEKuFs8rzfz5ks8503md7379ANf2LpNpP0e
            KJvECDE5lErTCEsfacxhWExMyBM4pKI01Jz7Aw9UvSSxaez0WKZrhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T13:30:16Z"
    mac: ENC[AES256_GCM,data:1Kb+pBvytY+/Orr9fw3DuilhOuiptVguTEehI/1WRiB6G41zZwBfbqZ/E0saQw0dKIgr70zEDMP2cNe08Cbq7OictYFAFxWS3x9olJ5figk15z6bCv3ud7Qft/6xAQHrcjpQ6JAXmqc6G6JkQwx9IYhr9/9PpXS5aTeJHnwsvD0=,iv:ogqKyIZWG2gljeL55c7cPSTCa6o8nrr12paaB2vg16U=,tag:mIJtLI+4jx3C3R5/sQ2tbQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
