apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9J2UhT4wDm0axrYxRBdDqKO5WPDaG9DPjF3tYLBMNFSOgKr3QrLrCzRdc4B3CS5vIO+Bc0BjYmgxq3hCTFJXR+fM29caZ93GdDpe65d0MNrsdILsWIo7Le81L0Z1jtJduzuvpA0EkBN5rIpTxqtnRfFyoQS/cUZSruYEW3ABU/862M8lN/PfSebzMo+iPGTHVNU1adA7H/32dZZ9nziTn5E458ihloQeAdY8zWoLsvBvpq5jJnZtHYRNsu3dCzr97sbbPDRPPdimqoDWYtsxrrmkHKRqRivxLsy0SOykYCGtD7f8CRGpbwT/NLWbwUB/GfwbdHetEGp+TE/2Alh8GnLdbXj9kPaUCxDFxyeQvve6Clsyi1kiIhTB9w3ZVyWk,iv:AEiDsXcfVYWx6glkRhVtbZppOLC3Y/kpH/W4ZY6+dwY=,tag:UJNZgRxmLaQt/Hg/+D9U3w==,type:str]
    identity.pub: ENC[AES256_GCM,data:/ZpE+H6M/oY6MssOu/e6e7oAxIEZQQV73JJNy2uFL+7qpI0znA8HaWX2AUjZrvAujkASPHl/5PrzVQWC8B5bPAL+uMw644iFl0QdSj2YQb2JvGOba+Ggd2xaT+aHiTSbOYfeG1p21qcGz843ReGrody0Yr5YsB12VfEtqocHePPzfTxLVQOLiuc40HvkeVl9Dlztd5dDQz3OsmD1LX0YbqKhzVwz2ADs1o//gvBn3AO8q/Gcdlj90DzBOICoLEBPQP0ktJptnwMFPekCVw==,iv:lgonrdZzkzXcokNoGShs/pL6rswLK0229JaBMUXNoV8=,tag:kjUMVTTWrb3rMC/wPI8lYg==,type:str]
    known_hosts: ENC[AES256_GCM,data:O6ZiY+QmH9rWo4sK/jVgE9fwRdTl1GdNPc0l0c48vmnfNe773Hk4FL5Qu3m413GiyoAlwR7tijxf/+vNNtIB1fDSxF9J7dbX+YW2oWXDYrKiVMBrUcbx+T8nvwPjXKME1dDQYoF7jqZ0uHIa1eb97qZ0vwYXO+LCFMDN92dm+RYFCbl+qsCxtFWRzH/BWZHzDSRnz3tspzanno2c0P0ifs5IiVhS+oMWARs4,iv:86NV8BwH7w5q/R8v+/sS1MNkihhsoyEy5xRGRAupDs8=,tag:wLznLudi6XSVB8nP0aDB7w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN0xDS2ZlUVYrd3JPUk13
            YW53RldHMmVIS2tzSDJZVVM2VjlBaElKVTBnCkg4QjdZMTNJb1ltQTNGQ2VlWmpw
            K1BBQm9aaG41SFZNTjFGeUZCMHV1TDAKLS0tIDFMSVVPTzZ5eWxKZFR6TWRNOXlZ
            a0ZkSVRJRHFGWDZIaGpHd2xaYlgzeUUKXoKlxbO8rMJc7Dy+N/NOwD2eLTYCFqjh
            IBSviQizduoGHzOs2zvtGGLLX9aCdsIK3vHHiRGegOq5ph6vguQ3dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T19:58:35Z"
    mac: ENC[AES256_GCM,data:fufInBN4n9E+lfbQiUF3Ub5rdZ9MLAfBOLcgQ6bT1fHXVLgjJ49thHGeti0m51SeVVD0KIEb6S1fCEKntkq0BAU3KIRC4iQnZ6By9jKwedFUTNNIjeHuYd3v7HWNjoNZRsVUuWk6gCBVBnbnbRLDrEx6rUNTS3j5EhVuoZIUNmk=,iv:Kdj3egRhTBnNE0u1BednRCu+e/f3HqLy2stfdb13nUw=,tag:nSL74Vm95PY2OZuNl4yzzg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
