apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SoHKEoNPSRD2u0EmoW2uKsP+z9vo2GFNE/HnMspI89wcp5MRWF3iJkPOZARp9SJScGv37t0q1BKu39IgkKvwM4WTHSvdJT2XWkLgWx3TzXfo2JkNGrwgjsm49JIZOWLlkw3UpK/uIo0asHVq82xtA9aB8hr8uwe/QmX4ES/5Z/ybBQrTExer2+bppCrFDNLyMd8zapLw+CAkgKAavAjm+H8IQ/dHME/0U/rsgKcdh2rxDTjugogG1npVJs5VoPFVqSPP9TTAeSObWVkJGJGNB5Tol3vhwqWfGl67Xo9snZNy0e5ghDV/iCbZC04JcSsffFsn4X+UE884ldSlQwqgwOHXHXcAyhFWnBMfVYEgh2bt++bdElPfWMzj0vh/efBv,iv:O0eE8xOR33AP+reysFXBCnoovNf3iCMzxRPuEUU/HUE=,tag:g1Ho6mOOVO9Kh3Oont5v2Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:B7glnwueeV0xxuuIEj+Yic4FpUqHSzFkj/osVElBgrthg5rm5uUo7/OHpVA26i6RNcotyUsoJILfVoQziL23QLwy7jpfN7uPHNsj/zCsLjgP0SCSRIfQaHDZJTMN0G2Qv0CUfisXgeFA7hp/l73qUCnlOj5MnxkMqGOGHRbUb9K1QY/yalxBQDgIoj7kvgpT/1BZ4nbZ8Oc1j8LUTu6/90n01trTtWuZih/FygxN63kGX2UWKZ6d/rBfNZN2Ob2MZ0mDcNb/IZwtcxGVJg==,iv:GhTEYh07Hkgp59NXTQtgFpXhmSSQM1EZR2W6bxesQEo=,tag:fLoC58mnReD/9eWbRjnIdw==,type:str]
    known_hosts: ENC[AES256_GCM,data:4REOAeLqZhyY8chiqrewTM6VFWBGQLSHcE9oMwuYHc7bNi5newbEJHPsS80DhEIVRlv7Ut5CATXycDCzeXBHqMt9l3qOqzdZnbz9hmd+Pa5SiBd4cggsv85873miAAcSFqV0TZn6tw7a6lzQ8Lbv9zuo3mVpDKo0rTaRy1iNBYiBhCJ/30VN/vXtuD5nxgMyH3lA4K4vSG+icF/a+TP6gH2Yhp5bC1bK+vv1,iv:TChr2t2sBqLKNC+PuC90XptIfcfyWTm3xtT3HXUJIoA=,tag:4nUkstvBN851nA7H5j1NAA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQ3grc01WSTZYbXB0alU0
            bjBoU2RGRGFWN281N3ZsTVJ1M2x1SUJPSW1nCnBaSDlaZWtCSjVZb1VKeTJYL0FU
            K0FKQ2hHT3NMbHhZM1Q5bm52UTFSN0EKLS0tIDdPZFMwNmQrNkFXNzFSbmdQZlJ2
            MkYzVjJ4L1gyRUhTeUxuVUx5NGFxSjQKmZ+jBZIy8HzGj71L+wDoTjlL4WZHvkwF
            4IzPnI6n1P9n3mjMSFkI9tmxo/Y++5VE1oPNSWLZI1IFsiLiMkW+kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T20:17:59Z"
    mac: ENC[AES256_GCM,data:T9y6Hv2UEZJU/u+Xl3QowzYb8V4dh/MmA6hunsRDYI33If0zH8E0FDUhecL1OcUF3NZqeg6K2HYf5qzN/GBQWFC4PQw0YBcVO5OKLZP7GWVNeUfrOkJj1IXat1LCAqScOF0/TjPlAuPsEWHeBMksuvkMQtVqatpUzI5MPP8dJfQ=,iv:BGV4hi1cTgEEcwt/y1re3elB43ljL5q3eBcPjAXgvSM=,tag:p6PNkFrDZWQiE/K2TvHUBQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
