apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9YF5wU21Je2j7EU8kndb1M0BJhAKyNMQbxnid++sJUI9IJ0n3msIzf+wsrntOEj8h2ugbHBRca2D/sQorQwP07aI2jtdysWXeyzLhkGIOMSFiVhf3O9LDxM1ZCG0EtI+mBX5HAcuXvicGRcN0uRiL9Mhg48GsITwz0BgmvpfmBYZ/Ox7I5pPHxvG2RIiG1e98PferTbC/M1Va+OYpc7ojpfW3B5oKIlZuQNoNAQ56EEFJCgNV9jrjCf5Ka9RfDOgVynayf75YE4EfVrOfhPYccF7gwm1eQ/gH84zjhQeFB+2e1y3m5uRyWxeCxC6SN8lro+/WhhVtPUNba1mx8MwSDyTtMgmxSmRGt+WOpWSQfEWKf1ftHCUOf0ESq6rW+uI,iv:Ny4O3EPCloDITzTCAu9LHah9ZSNI5EO3Siy7arzWzgQ=,tag:uo6sDTqzOGujb4U+IQsz7w==,type:str]
    identity.pub: ENC[AES256_GCM,data:nyA/gCY30+Pua5J7L6b6h3gqumdcVK0OgN3dZUueOuKlWqBBsQWCdFA9ZMj9hJxph6j7HaPbZsyRX2ywglIS+A3W1cleAQQbm818mRz5KtqIWyrcfeKVlo9FetesQoSEXNKjc4B3PXbwwlGiqNmjP4vsHVp5wyXo6hhdXXZ27AHeo3SVWONDr43/6GkPVggPhP6yalq0+q3H7ypsybwig0PtiT756eNj7eyXMVXRVKfhhtrpeTJDB3YIZW6RomR6EVOOm6VDMXdqJ5qrqQ==,iv:OLUmf3hGHwvjyqVzJ5iDafsN9WRw4sPr8lGblXNwE2A=,tag:oZUbCVAT8tG5XQeUIEEv7g==,type:str]
    known_hosts: ENC[AES256_GCM,data:n1EPeWezZmHlL7HTUie8zoCiMxTROCwU/ssCCASTUtIjWPtre4VNqtPlZ8nokBHYY3QM3npw9b+FNmROvf9lA9yiFMSJOIHIG3OCyPOo/wf5p36KOSJr9sO7EAZjrGYjrEVItoQfJj11nQp6q7wcMabHLBIl3GQ36xwM7pURrC5KjBqMuDCYzXQiy0KolV3/GjeRAT6b1xUbwlYAhfq2sbmNMGcglSGkYxu6,iv:rudn4iMbAs9THu71mmEOk4bNSZpH38TUtfsnq+5SAkk=,tag:uy1zbbKRgMwfmSKghJEnpQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSXV0R2MyMEJIUmwvMCsv
            aGF0cWtrM25VWGZtMjVzME5UV3JqNlpOWVVvCkxtT0pJUlpNUUtpTXZzYm55Wjlz
            TENWbnlNdUNwWDRQTmNmWm9ia0pydmMKLS0tIE5JcFU3YXJwS1pNTGo2b2FFMENh
            Y1dhMFRoNHgxWVQ0NUVBR09mSlVna1kKQ09iuJTJRJhZ0JL1NdS7hArCZ5jkhLMj
            cbrhVBExezoJwW2Fv0lpFfzjl0CQbFm88f+eY1R4wseljHsInOpo1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T15:25:38Z"
    mac: ENC[AES256_GCM,data:DmQXSuUl67HMNkB+7RxUmwf2U9/VEVcYEAauBC5PZGidcLQekw5rlagOvMdg7Zeh84oqAGhT2hsc/c6FlhLNThk2vHeLE8xgHqgv5ylDI3y35EzFfs6XqPUwALuMuVL2jv7xkkqzLcnTZrXpZKP6zFumbaXNfSr1qvefhORV5fc=,iv:XE7s/UZghK1cO9CVKv6o+5/SNHuYuU9OW5j9U5p337I=,tag:otDgow2ExarkVoGFYFCodw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
