apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OlUec+A+yxN+2x0+nuo/VzgTt49ULf1F2bAis06PdOxS57VMn503XkPpgH25XxfneSfKp2DOdKPyET3K0MH2+eeN9FURSXpCf3B/COtYq8MQ3cVdSq+nMYq9rkDV4O2GpTRgi9XyUJow7V/NgbD/6FS59n6krHchAnQVwzrpokEI2Kb1xt2YkDZtNf5UlS0r9xrSsQWVJ2NAfw48MYKaPPRvU67Rhn6uYpfO60zMp+IzAen+lREEpZYyWWGAB4j7OnSpAEJ2uBBEemX5hHp+bUBENSA2S3qNkfJqfLD5WhfWpspv5D3zBYsTIqX0ocuIyteYgqJ3XBBB10hYVB23n0s29t3oTC0jAJbgC7/JRF+aA6WUjS8hH+M6SVAh4meA,iv:AcKnuVxxru1xNo/rtQ6OiKnnlZ4uXeF4bNf0dOxePag=,tag:Hq66TDf1lp0NvKIgkO2a5w==,type:str]
    identity.pub: ENC[AES256_GCM,data:61dolTa7PoXiQeQziRYzzNkzRzlfU0fYmTO8usAKhn31PhSXn+MiHedL+JVOHK0hgZJHkpEjSGLp+mvAsA7SQC1ruJbZLEdYMvNmi1tQ7osPe/TSIZ80tJ8FU8dBAyZsrW2Q7WHRWneLZQUCp8HbJbNS+WYZU81/QYTcyvAzpCzA51Pq4vyMXZ7/roukIuvJAhiCIOSQNV23bIZqo1Ut6TjJX9sBbXbmxv/baRav8/rDhUnXCL1EUfgtvH7aOJrHQlSyNI7kh4Xxhr1xxw==,iv:U37NRQOUsTVOdEbpVW3I/MOrRa4XD0DN7133CF3bojM=,tag:bqlZl/YoB+Xjko6tgdj/Gg==,type:str]
    known_hosts: ENC[AES256_GCM,data:cWjrjS8ZvHtlNtkVhptH6LvMh+vSC13Ms9Y1oaB37Oa3UTWxT7Kh3/FRzKojJuCxG5pOFqhxHGtTN/VkVAW/yzIuHsfebzdzCJ8SNXIm7drkiPvy9f3/anKE4sYl7ZLWciFnJSWgNkbKpzfMzIh0fKaLuArbm/r/eM2tB52GY+OoHMnbIkrZjqvQc+7sOqyG25xIejLK143s6LlUd9HscS07UqMz/0rdTLoh,iv:gI3oX8zpx14unDQ/puHpyIdPhbP8oHNxNTS6dcPML2k=,tag:TrhdW6oliQiDJaOs4T15Lw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZWFBeDZZdkROWXNRcDBu
            emhIbEtzMkhIdkRISmF2cHhqem11ditMRDNZCjVwdy91OEdaOUpxQ3BSR2puNHlP
            dzZwQkxnL01XdmdzM1MrVFVHV1pFSU0KLS0tIEM5MHFvU09kcDl2bkdmcVZPd0JK
            NEpZWE1UZUMyZzluY2lZQXh6QldmRzAKOAhBtBhvigzBEDMo9vjH5p98OSCbb7rZ
            iiFG75xu4NwCb50xaoHaZyWqJCoVvq6h92NA5CY0p8qErXgXoTQjew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T19:23:39Z"
    mac: ENC[AES256_GCM,data:TCGsD3Vmi2gcyGgtm1nDgc9X71MDYtaoUcW0nHzR47aE97/hshH6T20f0xDIkkk+Vw174HnYQ8rXpa0OBpB8WijNv/VqZLkY43/8Z64sCbhVOIp95r3MwzGPRf5qrztjsP8XTJ4G7GXlABW0+uZoI7RMPVagfqnbM1hTX1sXOfQ=,iv:sHQrK0UaeRw8x9jGpOHHOUCLNdDN80hxyMq2sT29rt4=,tag:DR+nL3JRWaBjinUNxIKuTA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
