apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RHz0gx/p+Qap28T3AAEHR73atRvkzg+JVO96a/6emAHvh4PqxPgDcbMVCoPPmQzdDoFtXx5mTTjTyEYicZTnY8ob7pnNrM9xy6cm8DUZ1knktMqFQlaFylmjpc5F2L7CqeXCTVdx2iCv+KlQmgbJq63r+es/h3ySwBQi4odoSQ85H31Uoo2peyQ0SiRx8V779b6/L4Qp6K2NFdHzwXSUR7SpvYJt+sy1ti8GCkjH9UxOyp/PhdPd5nAARoy5MLonv46CIb0zR9MV8mPZAqQK5oo/FjguQwz86Guk3QMf0eysJVdU/XqvID2sHBFzSyToY4VqBquD7zZ4/VdQN0gIjp+XaYbHbYU363XO+duYxt0u8JQw3a4nMNTOUVk2Hlvj,iv:YnDOdas5bG0HTCNzkZ34CzDt/n8WBOhwJgk/IRcWYQY=,tag:SZl1AS0mP0mUUT/ZIp8W9g==,type:str]
    identity.pub: ENC[AES256_GCM,data:uSvCx26y8S0s34wzkTWO0CQUsTOL0Fd7CvT6c4DJQWgI4P3hV8XAFR3DWJRl3LPxJAT+JknFWHtZQP/uTORoajZvHpShpGQV7mWapbeLNLy6keDexeLOsQHTxhqoC797hZm0O0BKqsrl7RMYiAGO1d9VyEZ4R98N8RI45wzwul2bYeoUV6G/I2jO1XGVUQm6i8hN4idKm822a9NozlmFlXs5RF9z8A8MXeHhzunxVfzfNwcER+n+LMH5n2XMdy2XGOuxdfOH3ar34EJ5Nw==,iv:Pre5OmL6iXdLkzAScAY0PyYbfCke9Yuhfx+VHIiTvpM=,tag:jr3/6kQbzKmZxd4ughx08w==,type:str]
    known_hosts: ENC[AES256_GCM,data:jak3+IbtXJtBpMc+HdQxfKpdQyFa15zCN7T33t8U7L20TT2ty8f5CfRMvSqsC6mQsNYsv3W7ZnLterpJA8OccXvZOOuErcR4YGzMstf+3nlJFFEduzUH/umr1nmMSfVe5finnBAVlwvb95JGcixIeYpIXqPJwT8jORIGksyERAkLb+EgPads8pQzSSnG0jUmianK2hCWlDmqDINOjYml/7SDgDnByt4fCVOE,iv:fbR2Lj0wQ+/Zph6oQeZg9WrLZGV+Jc8aW1i4kQUMrQg=,tag:inDDXGrMMMu2Mn8FiqbIJw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZDRVRmgzbS9NQklGaDRL
            SDJMc29OVVdXNDRHajFXcXlxOEsyTHZ4cHgwCmZMam5TTk1mODFzYkNudGVVWW1W
            d3VFc200T0RDTXJjMGJMS0JuOFM1SXcKLS0tIE03QW5VVU81emJJVXNYWTkvQjRQ
            V210cStZSXBMTWhLZGI4VWJrcklucXMKzasFn969KzdXs9i0HltP8ppcTpDiQrRb
            RAyIheM2e6XImTYjN7J5K9KXm0quTGi6TP9kLM60/OtXkOzfSAOiaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-03T08:35:52Z"
    mac: ENC[AES256_GCM,data:eeIYDyyeqHCQB4QN1pJX+qLH9eZ4A7Y/SOc9NfpVnzMYmLsC7QcgNc4GOmQ3cFWuAQm7oFTis9oE/sj3IrQTHzklKO1sy+R7OOL+MH3wZVvACakn1+CEcu/HbCpBCkx5XOwDr5CvbD25KTLXaKqhWlnSS9bBIc9xQkLW7yxj4bE=,iv:AOiUUPRuWOL3Oukc0hZ9fopcx8u8umbIaMHBDOwlcqY=,tag:Rx5YsLWU2PqQYPPCSEUNww==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
