apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:36SdzfwR64ffagumfZCqpjCNOz2vST7/H6m4cffmcWI1NSekQRLHBfPJZlb0MMrMoWS9tBgDXED2N/Tu8nl/rYCcLGJo9Pc3HG+5azT54y5zneuqIiwvD4OAg5hlLsNHciaoY/E9j/KFJQcjzpODDhEO9XEdOejLA2NlfqYEH1rZ34b/yXHvErpOuEaWKbbnogGVKPya/z72RuTvEwaZJ8I6418gqK/XsEkUcPHkmmzcgta8OEmh2WDB07Aq/ZAmHAmX6z+MoerFGKFd9IAQ1IoUODm4kUfKDVLD1vQYkel1cFFknwB/2y2aYCb8zLfNa0ohaK3rsWJaseg/1TUlSO6Vpv+S5MLC+tku+if4mxNXcGQAXqC1oqyZXnP2RCQd,iv:YgRe+oviz+zNSNN8L12es6Pl2AguyObh0hdpA/+HWQ0=,tag:99OH9+OaxQJWGUZBZLqM7Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:g74QMkPhebYZ8kHcU8DhWKor6iQ0nCugNMsr9j7BxMBlQ+mAqYQ/kAzaPqWTuO5+/GbYz0iw6tUG0mj8FY0i70Qs9TDQq/awVGjZcG3g/pSM9T6e8SFdWwvR7Vao1noMV9L+lqqbu0qrL2qs6iIcv5RMc1nz4Tfb/v0Z4Xn1xA17QUdRLaIL7QZ2JY0H7cKgXzj62tnrLMvQuobA8Dk+FK6BgJoT3wKbSZ1+y1jK7CfUiCWTJ4BwkUKbtAjyfNKflL1bLBq1F3JXRWSMQQ==,iv:vtqY6BEQYV4xMRsBlq77M67iundnOgN3umnDQVaYE7M=,tag:SI6HA13UJ5Oib1yFk61LNg==,type:str]
    known_hosts: ENC[AES256_GCM,data:jyD3sQk9z32bKiPhXwSXntmXIjX21jA4jtPoMpHpMGNEJXa9Bb1BxnE8JE074o4YpkJgcuGr2Aj1XSbfDNHzHoIo6IHkTV0k6fbVZi8I9IukFa6ztQnedn7jhdx2jFXhmPITOmiKTi4FDATVmfBSp3ft9lx4lYe2wNR7+uCt43Pvwn2ZLB7wOHGkatjIoExFAy7Anj2PCHGT0+nW+R1YTyWkt3dGzRJ/Mi6h,iv:orLvwxd94TPBaAzbkd1f3/bPhdGsncTUP22q70sosUg=,tag:0trhuhJNSqtR2Jq6xRxYTw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWUM0RzVTZTNVR3M4cWJn
            Q2RPaENHR1p0KysvdnlDWHkxVzRTWFBwNm5vCmdCM0wxRE1QY2hLQkR4dk54cGM3
            Q0ltYm5URmVtb2M3TlNZc2tyeTFkczQKLS0tIFJNL1FGV0ozWHhMclhNTURMNlZs
            RzJmcUFKdHZEZ0Fnd044RmkrNUNGQVUKX9KFaH1bo/D1s2wT2/EmNx0a23CEcAcD
            LNtxjSkVe4E3xR/X6bQfD4KY5ez/LUafJM3nBNka1FEyCTh8SeJ4bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T21:47:13Z"
    mac: ENC[AES256_GCM,data:txWSjYqdX0+13lu9HdRq6AqrMVoVYgIq7QgXYjLI1AK/6GKVtTG04Ysmqnn0+lXxgGwtAx1mrwFWyihZxHNKYWhc+R2dspz+CnYZHWkSPp7afhO37APK7Mn0RGQ6BXrqZOXnX6g+4rEApEO9TSxZ+BzSOL20eUX5WXb43h/fjB0=,iv:THHhp8PRsQJ67LQil/fyGN8zwlqVs9M0aiV6ZX/HWk0=,tag:zkNnIayD7Ys2Qi9y/nMLKQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
