apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4p1cSwNf9+Nt4QEkGrhDaY1JbyKw52SQRLtPc4sx20x0+PqhSRlyCMh1M8zMNraghYyFef5BcuU6zklVj17LP+J2uK4HjaOQCFiqCeMy6l9SKCNRfrWVuXcpvU3KnG3tA6b5m496RKtWkjGREYMur3kz+ERqsEH4ELGRePZijpfEVmkSb9I0SSgRr7SrxX4KeYEFK9/ZY5ZGSr+ITfs7aF4T/9iILtRt1x+7o8N3jPZ8aVhkL56TQbUZA/tGd1wsjpv5UylRJrU7XMQrZq7LEtHNgsMkm5KOtjlovkiGdT3V0OdWHrFtNEBSnyAeEMD2KTLb9JklwNUD2Hcyjh9la54md3C0jWkkE0uCzZDPID2aRi722f+KzbrB+ErIpd90,iv:2wM4KEw7yanxQKQllBO1rgj7q30EH5vjpH3UmM6f6Gg=,tag:xnSlQi74fkso5QTchOtq0g==,type:str]
    identity.pub: ENC[AES256_GCM,data:qzGE4gs9Zu1I4pP+NCxSO8J7YBINnJnqIBi9X0Ersbe5tYODrMpy3ejRiraebBnBL/8vTfrV9R4DZcNw/5dGvTMqY196IdfV3Ns706GHoLB9JlGNNIca1EjrtQJRJnbfQYSelmFd3iYtvMGdn4u3vkfptfREyY2vRbqECtqDyHnkNVuKr3HJfYDn1n5PAdgVz8nA7S6imB9+jiEtrWOPPo88DihRTph5hnxOJjf0dYaFI7rRMs2Hu6KBpN6gzhjfFeth34MiryKhsmwU6g==,iv:IMTadLoga2bez3P0+tzlKXMozcnfnW4vt3ElVxb3MV0=,tag:NRJDUueDjC7FDc/U7mdJ6w==,type:str]
    known_hosts: ENC[AES256_GCM,data:5nNtwLz1Jl3DSY1z05A4Lj1UKbkajvocS7QE+qdUlgKoQRky7vVI6d26UFw+a2cMlDt94BvYpuaPYj0I3hwLX7rV4weyblkOJrxlQZu376TLt0N2/CylxjIVqqVf+R8pg8d2iz/Nim0SGwcFip2/mXq/tGdQlwApgd3n/wtSRHpu51acdYW1qmE7tDfnQanGtxVC+FA+oHlo7ouXGXPqdqc84qya31l8NoG0,iv:b68LqwGXSPtPKTLvYL663A6GVk9ADYUndxXuMct7Vm0=,tag:46roHxnlTiRZssXuNJTi1g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YTdtMDBYQkprcVBpNWRY
            UThQdEhIbmREb2RUVWplSmpDZWFzbTJjRzBvCnkrR2RWRVpyNysxRDZoVUNDcS9N
            TFVlQ3NxT1gzdmcwa2MzYWdTVVV6OVkKLS0tIDRWSHptbFpWaXlTZnZya0pKUjlo
            Y2MzNDByZ3cwYUNZYnNvY3o3ZjhWcjQKdFbFw92GaSawmjFeGAD+r90x9RGZ4xXu
            fa1DY7TNfvW8DmnYveyn04Mz7eFEOna/FekSl0Zs0rgZHgBIApgUCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T22:07:53Z"
    mac: ENC[AES256_GCM,data:a/sob/h0hm+MqTAQ1WwgfSvnmON8cXaazjnTGPDKs4LPDyrb8A//K8loZtY5dPOTUax+C2UQedOu1MXaiTbqMjWLixyr7oa0gqzetFekjVe0Y5guav3pIu4NU9zNP4EdujVRQuLOiu1i2Os8iQ09KuIWhdRtXwsB5oXXRNv/GWU=,iv:N1iXy8+onh4qJODqRwtfJNMTXxptUgX8GWJqNc1G4Os=,tag:5jm6E5/JbBRyNpdMHTXJOQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
