apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CYE88iQyijwfK9D3PH71Xejmw9Yql4ez39je9T8PyEyH5QuhBPGd6WtfD2dDr/U8W054Ystwnw7EF4diMVQvxJtsSe9oNYWvDjHn5hiZDrWRJ+m8jiTXPz3H5q0nhLAwgdeyMWWH9otwHXX5syANiDe04ZIAuT6CcA7Giga4DjwRBV3wMMw/cO/i5rOf5Kf7Y3DMF9UPRKNaV6iDpnfyJKuslLbGtbbHUrP+4RN4QpeRtOJgdcx2hpxXE7eLuIJzQpWrvmJ8Uf4jqclxKRGLfHQu4dyJpCLyHomad4dZBuSIISXLAv40B7yRHZlyWGzZLY6lZmjFSc0gyZ8IHPTds+eN+PUvlpmBHS6QrT9PCmVBfWaD1zAhEhmXj0ocXCE/,iv:Aczxt6kn0A0LJEm/tSDPKI4lWpse82KxSu1EBjxlQL0=,tag:IBgBG3wqBEQKF8mXTg2V/g==,type:str]
    identity.pub: ENC[AES256_GCM,data:sW1JUOH9ifPe4TprKW90hEfiODRUT53MlI2MpWZ3TcC+Zrc580VMILGzKrht8w/LLqHaXpASO6rvY/QkBEJtABDPNtysTEyHJqfO92Hy/vgQ8LBSvH4tlFDy6OUV5DnlZ67/DqPCFB99qL2qyEPMdnVz/MZEIS9x9klWarMqac6vYcLFJoGOm5LVX8ty3Qhy2gg25vsI8Xs8TeVtR+lFup5MyffSnQoUnV7KzbEQLwHrqKxkk74SyPofIN5P2C1H4bfkHkhLsESh6sKDvQ==,iv:C8RQDW77izL5abpQwahz+HeePxbvr6fAkPdFkux6oig=,tag:F9351eiUj1i7N2YD9lyYSQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:6LZVlNKWRQhcv0egtppp4qrVnxr3Gyrq5FJ6aad29UWtsVhzW1gLswi2zWV/jj5F4uldyTKKerQ1joxc86JFLF9opaJa79fi1LjEaLPOcWhI/JhtZIq8MTP6XFlWFA0MNnkeBF36Q6xPkuIBs26gOUpRDjz1Pux2rKPl9mrvHVJzKbAFnqvmEGFfdi4+H6sk/zfeMYVXwoTF1xsTE8luaGd9ZwVXdqdbfwuA,iv:iut+ZMY7zZfhgTAR0K4qEPfjfzKzpH9mPvHWdoltN9Q=,tag:ZtwPIJBCKdxw+RY7gYmmeg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UE5XdlBzWHhvL0wyZm5m
            b0JxUHYxYXo3YUtxSzRBMUlFNDczRXBoeTNFCnJpNTM2V29WdXd2WDEwaCtNakZH
            VlhhOUhJOXpkVjAwNG43czhuRmJsUzgKLS0tIDZlSHVuYm44OStPM2RMV296ZFk4
            WEZpSE1LRjFPUjFxdk0rdC9pL3N0aE0KARYtECuSlPdWyXUCo85fDBG2r33zW2YR
            HVKG5KPTOn6Ka3sIakyWBa346A20SE5WMHllE3iEyQBt5HnDFjJr9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T14:21:48Z"
    mac: ENC[AES256_GCM,data:pybFzpfC6GU8sIzlQ93KSTOAeVTGRWZCxsfCRpKD4eiE5e3r1gcOqmBicOPNzPIM/G2JJQgHo+qqZhtXENxUmFgM1V9I/la/4SXMccRnreDrJuY3tmhV2uOwLD7evaGp5IdBeM0zVFDJ/ItlWqZWVahtJPQ8NIOUT/ci6XZoRTk=,iv:Ovv1zyq131VkHoIPisi67UOsG1sr3GIZ9hlgRbr+0Js=,tag:Je35thyh8oFuXUwmnPxnKQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
