apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dkjWeXrirJtpWVjPeMHTx+uq2EOD/8sTOUFc3urUPDODouiW6i/tbaGNCQX22ozzPP6G0yi3iMuCKOITr+QWaxGRfjJiqEsL87NnVruS0FhFII6lmgkKKW2HR3XJ3eEO+RwE2Pd5K8wnPtEQFd7leoN3iJmGFAl0dt8kt+o8IbljEQHl0cxzAUNNCwXvivNqu8KfZr++On29fETM24MzoKcPSwTP6FG7lKCmM7gjQkuIFQ/A1Huz4eKCavkp91SJlXjx1fq4l/dvJkrLYPpfTjXFp5+SnaqmySX+KMmATH2sdUyqxK4zuzxSSs338mUtOXansGSIjE6zDIqasapUCWMTlEKfZCfVsqED9n4n0rQoEO23lYMKpU1nsm5TM/Hi,iv:F/C/GFrBok6slVosNzoOfx2WXuNudkSzqkAOaow0fkE=,tag:d8QZ6bklj9Fqb1kFaqYXJA==,type:str]
    identity.pub: ENC[AES256_GCM,data:D7s4MZYooP7zO1mtv3AK2H2uNlEfboXL0ZoIJufk+/c6YDITRxGzxj+tY1Uk3NDyornTlrzRQSoH+qP/UPO3idYU8/SMW7SydsVz7Q2/k5SNp6fVTMbkdV+Jc4YLBphbpMzUSepE3LVS78WaQjPCFTX2zPm74swJK0UMus5lY5/u09cR3W2BRmh39hB8ao5h6+kTvryZbpnfgphqrltDeY2Sp511XPkRpr/p9QdJn5x/CpvxoM8X5CCLKJOfakepQGikjWnD64xWJsTIJA==,iv:TY0Akja/+bNMJi71i969WxStO2JnF06CHW/4L1LqtGs=,tag:mwuNE/CzS5mfnPlDjwpZQw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Pv6NCN7NBdg26HaxHVGVUogYyWK8p9auVqdjgOZwiP/9eiyqECzXbC7GY0Mo+7oxSN+3UCfXFV+Ty40FxTJHylHzK4otGEQhvgo2iCAjeo76gffX4HNgBbs4OV6XmnUfHYckmF6NbRGra+UeMtBAkJ5sw2Unvy1+0o6JUINUAMBVdUsFCiEecIcZj5y5ZCM0im/NXqe+svjrrrGzMwJghZa52P7bRHZmA2bQ,iv:d4ZDTBjmw3gtowifvDvflfHLxQA+yQgWVnDCDcIuwko=,tag:K9fDNB6m4O7UIkwN9Fi9TQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERERFeFhZbC9remtTakt3
            V01RTmxvZHlLS2I2dlpaWndKa2JQZmxGOUZFCmxEREZmUU9DVGw0aWRSOW5aS0U1
            OC9ZOURyMklQcWo1YjM2dDV6RFQ4Qk0KLS0tIFE0eGk4R29ocEpsejhoSWdaVllJ
            T2VVQVJIRGpsU21kZHBLTlB3RE5IUHMKOVrBWY/ORMPtgjBI5ZEffSGU7WBFsrp7
            AU/5tGnKD2XKOaEqkS5pLUKpcxaqlJpMDZM7ZnG7WlfNbFIbvlgDFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-02T19:47:24Z"
    mac: ENC[AES256_GCM,data:3qL9Mk8foA1Tt4fU1d169xHgUesvcDxQtQoXGH97f/F3h/M19l1V3ewexR+zPGScf5kG5R0hUbG5i+bD56KRCUgQ3GgVSUYaaORvScEaKzHYAwRsYBL1osRQyKe6x+xwGaX+ANTqw7C2d6bs1OHrNDi50SG6SJERPcX/TZwBNpY=,iv:g6zJ27ZChLDOk0b0m9Bhusqg7xJhpA6o/SG3UYgM6qw=,tag:GP+NXarQibG3SAD6qyzNCw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
