apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/qIxB7sb0sH92o+NKi7YLdjj45ktyaS8KA8U1r+tdqFfC/lNSENwXV12v5GEhj3nGtIIY2IdgUsnH9aY5KBGV5YLJabTgQZqvCD4hjFpq/vMbKOV3UUbssXuOEV2x3KYCeLaEyQB5kuK8YpPHGc6mh6AKN/Rysyb78KYudaB+q3TMLu7f1OexMDp4QjO77ZUiA9QvbcNn2SBz5AfB1W0bk3UoiH2EsUT+1iL62dA32MJ9pUei+xhJvDUAhdhPDgXSjNd/mHVFleGjH+keDpOySMOmAReCrnF9S3OvZbdlFz34b/7PMfXDohayx9dCoKpzQeJ9yQuMIaUouQ+OXqd+RZ71xWlO/FfLsI2Sd94+quvotNN8ag3Ta1Hsa0zfXNQ,iv:pDKwfyRQMzLc19cPkV8euTKuiR7PArmd0kx90o9mr/0=,tag:QFKdTXDkIFMrz2xDAXnTYw==,type:str]
    identity.pub: ENC[AES256_GCM,data:QbAqOgGsqdFLXWSVKUvHeKV7JEbgmb4u6WkvSklmJ+NiM75TeK/2x2IDtlIpAnewIaFbF4C2wFeLwY5YwYv3vQmr6XcGNllSiOKU9IGUWVMHSIuZN0Cy1O7Dbk3Hfq5srKQibYPnlSpqz0TP/BDSDzrkDzlNiBeGE/MQInSaTX8yrOsK0siau8gnwdlc3b8RTdazcS7/nzHbCERHnwSW7zQRPLKckZpTm5hLE72EnU6UsnGdop+Nps42/Vu+QLABMtjWer0tVspqbKbbLw==,iv:nurRAdICDqVAYwxTDEyAG+b2kMKX8i9tri7bV9mP64Y=,tag:k2YY0mqXVa8FwwUyE6UrBw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Azc8ycRlCibjotCZOTC1bwBUEERfqhHmghEK6aBNi9VhlNnbgL4VsBkgzpx8ThjcqjpQRgmYWmUpBsmjdvcg8uBIbcEyEZuUZKWGIUc0REmwistkatXINsY2n4oPGF71kwn6/YpM0aw+f2Zvq//s0VYqaxommnYSE6eWmohgdl/lvbxnRhaR8kfRoieoMsFmMQSoc3Ei3qsOtj8HvqcP35FStkhI9CHtciB3,iv:l15NHHIXhvMWS8s/8Eyqd4fyPdaN0omhnC4Z5KDzM6g=,tag:a0vxQaGCoYNasRCbkPYtRg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UzdkcnNMc1ZUK0gzL0tB
            YSs1SDBBdnFlSGpxU05LMGtod2JCcWNJVFRZCmNMTzdKNGlMekFITjcxRXFWU3Q4
            ajlpVS9DbFhtemFmbnFJOHdBOVRQWGsKLS0tIFpSRGwxMFN0a1pTWFFYRnJvSTUx
            TUlhMUhlRWU3eHZYZThsS2J6NGNKWWsKSNvdK/o8dnFQZnw9XetvgnzJOpSXOikS
            EEhiHXOp2Cictm/sZnAW77P9n8AzzZw97B+EzuwlSKXqjONEhdNRKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T07:43:39Z"
    mac: ENC[AES256_GCM,data:Ih93XIkqw6KLMqspvChJbCtm0lJVXzQowHKGovUuOb5XRsBwz2g360AJ+/z3HVrSzKq948oPdA2sAy31UOVva6OYtMvoP+Wo5J4uY2zdKy0Byvdovd3oZkmx/rzvbS/8QpQKEU4gstbNl+Koef8Dp0+KeL4GSdGKaaeQTYJftV8=,iv:mLj+lDH4RNlLjxfRLI+KZuOG2IWBrz/cVPDcfv5npA4=,tag:/JbK6gn1cLlP0Zct/ouUUg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
