apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Kp/wcD3MpXKOVUGOYgu5GKJp2fRMrYLQD+edPmdyXlhgzZ23d/4dWU1TMtx2mkSTVNxfjtm0WuMFL71rSsSoFtKr605WZj8igIY3KLTI9YYhLPKI9BCFZiDmbNQraHjeAo3lkYbaR2yDXxBmjC+LtjfImSrAW1qATsoF2bsnmNbGggRZ0rn5J5jBWaX1acOMnp1YbhpNtKB4DxUBzKonoD/CTwuRB9AThlj3honFk4PLwXDTehg9kJ5ZL67LuG7FaBYkT0Qa23XzfIhlTRJzM8+X7fugbhxVQ7EW6grf+fIgf+l4V9soxJ+CHmPF4P/eK5UIrwGKp7J/wuAkrgGLENHVr+fCljvsvrrOipN9Qr4oaXKXv6H2wBtXtOB7NrEk,iv:VBAzDSxptgCvc2XKA6poisFdR6z7p9FCnhngSnLUGkM=,tag:ByFKFDL9iLydVrBsiJBcXg==,type:str]
    identity.pub: ENC[AES256_GCM,data:PzWIeunTcEonL0cjuEOzdB+XK7ocJfN6WBcz/WbwxkLglQav3hQctv0cgin/i3A5cWQJpqwZ60DOiRM5JCYm1ZErg4mTEpQcfMkAjClsv1XMVit8jojRsCegf7XDKHaLWG6sYNiVfmoVyHP86x2P+WmyHPkWx2URc8ZsuNLvFNZdED44UVmfEXTMXoK/paaWYwQ+nL0SGX5ZLkXPsfASX7NUgayvPHzSbS6jPdJFe0DenMxPUi4ZWdWgdqBgP4/uHFJ2WohkptuN9XuaIQ==,iv:LlpZqozw2m5fuCSekdycafECAWd+kOmk2ZzdglK0ZkE=,tag:U9m9wNxdAauOokMKYxIqBA==,type:str]
    known_hosts: ENC[AES256_GCM,data:jEr477XwMadGtojLWtzUHnKDIjsp4qVMA3q2+86hQmwOjDynipytA8jS6Al6JwPdASGhxP2cnk8dQsNWvqSUgpf2IIs3/Dh8yuqS7voYrFEQzYFWl5NAyijPumGFHFyFIHZdQYhXtGprzSkRZw/FQ8vqQsQi1i8Mticy23qErG302kOK1tAMNVNMaSyA3L4Tg1YBRXhIexXeG1tWH3eoT66QwUQMQQdC06V3,iv:fEHYWVm3a1UZr0VRGDmMMupSoAJi7f8bUeaeOGU8H0A=,tag:/usIhTapVMNcDTJyva4ETw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age192sz2ggzhaq86rxtgztmcnzj2uq5tvdm9ld6pjq7yslexvc25czsxt2xlv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMY3ZQaW1tbnFic2E5cmQ3
            anBudWk2c1YzQklxYlFwMXozaHBaVlZPN2wwCm4zNnIxZ2o5YlpzWVpyOWNmS2dP
            bXEyTWhGanozSHc1eHJSWGZlTTBpZjQKLS0tIDYwVmNrQWpVZ3JJNllSemliUFJL
            WWhzS08vNG5IWWtTT01kNUVDNnlsQ1EKLDlL+S0OPV4nNniCdKSVjvIMgdcS9un+
            Gc1nX00Ue92906IMBg+TunB5ulZPuKk5p8LaX8OygVFZ91lEPu/dvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T21:08:51Z"
    mac: ENC[AES256_GCM,data:WEB8Btm925uldRWBi6BeUH744ryieJt8ek5B9A3EbobcZEKO8K9WKXXTGAvQEM7DGWwK81CEYZ9RQBOLQTSVlxvFC6k0WiK5mwTvmQK4CCE2lhjlMCCRHOgOlL1S3uASDQigBGCxOPYedOBP4+hQ6jKFE9MoGQ40vqWvSK0b3Ic=,iv:dJalTBtfAFS2048mQ0MoKGzUjH1S2gNIszmP+gSSi2U=,tag:FDnurY1YtoIOsIviu5L0+w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
