---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 20.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      stopAll: false
    plex:
      serverIP: ${PLEX_IP}
      additionalAdvertiseURL: https://plex.${DOMAIN_0}
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
      media:
        enabled: true
        existingClaim: media-nfs-pvc
        mountPath: /mnt/media
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}
        integrations:
          metallb:
            enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: plex.${DOMAIN_0}
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          ingressClassName: internal
          integrations:
            certManager:
              enabled: true
              certificateIssuer: domain-0-le-prod
          hosts:
            - host: cs.plex.${DOMAIN_0}
      minio:
        type: s3
        url: ${MINIO_S3_URL}
        bucket: ${MINIO_S3_BUCKET}-plex
        accessKey: ${MINIO_S3_ACCESSKEY}
        secretKey: ${MINIO_S3_SECRETKEY}
        encrKey: ${MINIO_S3_ENCRKEY}


