---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: code-server
  namespace: code-server
spec:
  interval: 15m
  chart:
    spec:
      chart: code-server
      version: 14.4.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: Europe/Berlin
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: code-server.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          traefik:
            enabled: false
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    credentials:
      minio:
        type: s3
        url: ${MINIO_S3_URL}
        bucket: ${MINIO_S3_BUCKET}-code-server
        accessKey: ${MINIO_S3_ACCESSKEY}
        secretKey: ${MINIO_S3_SECRETKEY}
        encrKey: ${MINIO_S3_ENCRKEY}