---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: vaultwarden
      version: 29.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      stopAll: false
    vaultwarden:
      allowSignups: false
      smtp:
        enabled: true
        host: ${SMTP_HOST}
        from: ${SMTP_SENDER_EMAIL}
        fromName: ${SMTP_SENDER_NAME}
        security: starttls
        port: 25
        authMechanism: Login
        heloName: ""
        timeout: 15
        invalidHostname: true
        invalidCertificate: true
        user: ${SMTP_USERNAME}
        password: ${SMTP_PASSWORD}
      push:
        enabled: true
        installationId: ${VAULTWARDEN_PUSHID}
        installationKey: ${VAULTWARDEN_PUSHKEY}
    cnpg:
      main:
        #annotations:
        #  cnpg.io/skipEmptyWalArchiveCheck: "enabled"
        mode: recovery
        password: ${VAULTWARDEN_CNPG_PASSWORD}
        backups:
          enabled: false
          credentials: minio-restore
        recovery:
          enabled: true
          credentials: minio-restore
    persistence:
      data:
        volsync:
          - name: config
            type: restic
            credentials: minio-restore
            dest:
              enabled: true
            src:
              enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: external
        hosts:
          - host: vaultwarden.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: false
          nginx:
            enabled: true
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    credentials:
      minio-restore:
        type: s3
        url: ${MINIORESTORE_S3_URL}
        bucket: ${MINIORESTORE_S3_BUCKET}-vaultwarden
        accessKey: ${MINIORESTORE_S3_ACCESSKEY}
        secretKey: ${MINIORESTORE_S3_SECRETKEY}
        encrKey: ${MINIORESTORE_S3_ENCRKEY}
