---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  interval: 15m
  chart:
    spec:
      chart: unifi
      version: 23.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      stopAll: false
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio-restore
            dest:
              enabled: true
            src:
              enabled: false
    service:
      comm:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      stun:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      speedtest:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      guestportal:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: unifi.${DOMAIN_0}
        integrations:
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
    credentials:
      minio-restore:
        type: s3
        url: ${MINIORESTORE_S3_URL}
        bucket: ${MINIORESTORE_S3_BUCKET}-unifi
        accessKey: ${MINIORESTORE_S3_ACCESSKEY}
        secretKey: ${MINIORESTORE_S3_SECRETKEY}
        encrKey: ${MINIORESTORE_S3_ENCRKEY}
