---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  interval: 15m
  chart:
    spec:
      chart: unifi
      version: 24.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: Europe/Berlin
    global:
      stopAll: false
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            dest:
              enabled: true
            src:
              enabled: true
    service:
      comm:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      stun:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      speedtest:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
      guestportal:
        type: LoadBalancer
        loadBalancerIP: ${UNIFI_IP}
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: unifi.${DOMAIN_0}
        integrations:
          traefik:
            enabled: false
          nginx:
            enabled: true
          certManager:
            certificateIssuer: domain-0-le-prod
            enabled: true
      minio:
        type: s3
        url: ${MINIO_S3_URL}
        bucket: ${MINIO_S3_BUCKET}-unifi
        accessKey: ${MINIO_S3_ACCESSKEY}
        secretKey: ${MINIO_S3_SECRETKEY}
        encrKey: ${MINIO_S3_ENCRKEY}